web:
  build: .
  working_dir: /data
  command: python app3.py
  links:
    - db
  volumes:
    - .:/data
  ports:
    - "5000:5000"

db:
  image: mysql:5.7
  environment:
      MYSQL_ROOT_PASSWORD: pass02345
      MYSQL_DATABASE: ac3
  ports:
    - "3306:3306"